### ISSUE TITLE
PyQt is gpled yet this deritive work is BSD license. 

### ISSUE THREAD

**Issue by ianorlin** [agateau/mup#5]
http://www.riverbankcomputing.com/commercial/license-faq

Is from the people that distribute pyqt. 

I really don't want to see you get sued but pyqt is distributed under the gpl and yet you claim that this can be bsd liscense I like this project but don't want to contriubte to one that violates the gpl.

**Comment by agateau** [comment]
I don't think MUP violates the GPL: the 3-clause BSD license used for MUP is compatible with the GPL, see: http://www.gnu.org/licenses/license-list.en.html#ModifiedBSD.

It would be a GPL violation to make a proprietary version of MUP and ship it with the GPL-ed version of PyQt, but I don't do this.
